# Generated by Django 6.0.1 on 2026-01-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TrainedModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=20)),
                ("fx", models.CharField(max_length=20)),
                ("trained_at", models.DateTimeField(auto_now_add=True)),
                ("model_data", models.BinaryField()),
                ("threshold", models.FloatField()),
                ("feature_cols", models.JSONField()),
            ],
        ),
    ]
